name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install contract dependencies
        run: npm install

      - name: Install frontend dependencies
        run: |
          cd client
          npm install
          cd ..

      - name: Build project
        run: |
          cd client
          npm run build
          cd ..

      - name: Deploy to Firebase Hosting
        run: |
          firebase login:ci --no-localhost --token "${{ secrets.FIREBASE_TOKEN }}"
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
